issue_tracker/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^issue/new/$', IssueNew.as_view(), name='issue_new'),
    url(r'^issue/(?P<pk>[0-9]+)/edit/$', IssueEdit.as_view(), name='issue_edit'),
    url(r'^issue/(?P<pk>[0-9]+)/delete/$', IssueDelete.as_view(), name='issue_delete'),
    url(r'^register/$', RegisterFormView.as_view(), name='register'),
    url(r'^login/$', LoginFormView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),

]

itracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('issue_tracker.urls')),
    url(r'^admin/', admin.site.urls),
]

issue_tracker/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings

# Create your models here.
class Issue(models.Model):
    issue_text = models.CharField(max_length=255)
    issue_description = models.TextField()
    issue_creator = models.ForeignKey('Person', related_name='issues_creator', default=0, )
    issue_assignee = models.ForeignKey('Person', related_name='issues_assignee', default=0, )
    issue_product = models.ForeignKey('Product', related_name='issues_product', default=0, )
    issue_kind = models.ForeignKey('IssueKind', related_name='issues_kind', default=0)
    issue_priority = models.ForeignKey('IssuePriority', related_name='issues_priority', default=0)
    issue_status = models.ForeignKey('IssueStatus', related_name='issues_status', default=0)
    
    def __str__(self):
        return self.issue_text


class Person(models.Model):
    person_name = models.OneToOneField(settings.AUTH_USER_MODEL, unique=True)
    person_dept = models.ForeignKey('Department', related_name='issues', default=0)

    def __str__(self):
        return self.person_name.get_full_name()


class Department(models.Model):
    department_name = models.TextField()
    department_type = models.TextField(blank=True)

    def __str__(self):
        return self.department_name


class IssueKind(models.Model):
    issue_kind_name = models.TextField()

    def __str__(self):
        return self.issue_kind_name


class IssuePriority(models.Model):
    issue_priority_name = models.TextField()
    issue_priority_weight = models.IntegerField()

    def __str__(self):
        return self.issue_priority_name


class Product(models.Model):
    product_name = models.TextField()
    product_version = models.FloatField()

    def __str__(self):
        return self.product_name


class IssueStatus(models.Model):
    status_name = models.TextField()

    def __str__(self):
        return self.status_name

issue_tracker/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Issue, Person


class PostForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ('issue_text', 'issue_description', 'issue_product',
                  'issue_kind', 'issue_priority', 'issue_assignee',
                  'issue_status')
        exclude = ('issue_creator',)


class RegisterForm(UserCreationForm):
    email = forms.EmailField(label="Email")
    first_name = forms.CharField(label="First Name")
    last_name = forms.CharField(label="Last Name")

    class Meta(UserCreationForm.Meta):
        fields = ("username", "first_name", "last_name", "email", )

    def save(self, commit=True):
        name = super(RegisterForm, self).save()
        return Person.objects.get_or_create(person_name=name)

issue_tracker/views.py
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.forms import AuthenticationForm
# from django.contrib.auth.forms import UserCreationFor
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic.base import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormView
from django.views.generic.list import ListView

from .forms import PostForm, RegisterForm
from .models import Issue, Person


class RegisterFormView(FormView):
    form_class = RegisterForm
    success_url = reverse_lazy('login')
    template_name = 'issue_tracker/register.html'

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)


class LoginFormView(FormView):
    form_class = AuthenticationForm
    template_name = "issue_tracker/login.html"
    success_url = "/"

    def form_valid(self, form):
        self.user = form.get_user()

        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect("/")

class IssueFiltered(ListView):
    model = Issue
    template_name = 'issue_tracker/index.html'


    def get_context_data(self, **kwargs):
        return super(IssueFiltered, self).get_context_data(**kwargs)


class IndexView(IssueFiltered):
    model = Issue
    template_name = 'issue_tracker/index.html'


class IssueNew(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    form = PostForm
    model = Issue
    fields = form.Meta.fields
    template_name = 'issue_tracker/issue_edit.html'
    success_url = reverse_lazy('index')


    def form_valid(self, form):
        issue = form.save(commit=False)
        issue.issue_creator = Person.objects.get(person_name=self.request.user)
        issue.save()
        return super(IssueNew, self).form_valid(form)


class IssueEdit(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = Issue
    form = PostForm
    fields = form.Meta.fields
    template_name = 'issue_tracker/issue_edit.html'
    success_url = reverse_lazy('index')


class IssueDelete(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    model = Issue
    template_name = 'issue_tracker/issue_edit.html'
    success_url = reverse_lazy('index')

issue_tracker/templates/issue_tracker/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    {#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>#}
    <title>Issue Tracker Dev</title>
</head>
<body>

<div class="container">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="row">
            {% block menu %}
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="{% url 'index' %}">Issues
                                <small>dev</small>
                            </a>
                        </div>
                        <ul class="nav navbar-nav">
                            <li>
                                {{ user }}
                            <li>
                            <li>
                                {% if user.is_anonymous %}
                                    <a href="{% url 'login' %}">Login or Register</a>
                                {% else %}
                                    <a href="{% url 'logout' %}">Logout</a>
                                {% endif %}

                            </li>
                            {% if issue_list %}
                                <li><a href="{% url 'index' %}">All
                                    <span class="badge">{{ issue_list | length }}</span></a>
                                </li>
                                {#                            <li><a href="{% url 'index' %}">Open#}
                                {#                                <span class="badge">{{ issue_list | length }}</span></a>#}
                                {#                            </li>#}
                                {#                            <li><a href="{% url 'index' %}">Solved#}
                                {#                                <span class="badge">{{ issue_list | length }}</span></a>#}
                                {#                            </li>#}
                                {#                            <li><a href="{% url 'index' %}">Frozen#}
                                {#                                <span class="badge">{{ issue_list | length }}</span></a>#}
                                {#                            </li>#}
                            {% endif %}


                        </ul>

                    </div>
                </nav>

            {% endblock %}
            <div class="col-md-2"></div>
        </div>


        <div class="row">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>


<script type="text/javascript">

    $(document).ready(function () {
        $('.expandable').click(function () {
            $(this).nextAll('tr').each(function () {
                if ($(this).is('.expandable')) {
                    return false;
                }
                $(this).toggle(350);
            });
        });

        $('.expandable').nextAll('tr').each(function () {
            if (!($(this).is('.expandable')))
                $(this).hide();
        });
    });


</script>
</body>
</html>

issue_tracker/templates/issue_tracker/index.html
{% extends 'issue_tracker/base.html' %}
{% block content %}
    <form action="{% url 'issue_new' %}" method="post">{% csrf_token %}
        <input type="submit" class="btn btn-group-vertical btn-primary" value="Add Issue"/>
    </form>
    <br>
    {% if issue_list %}
        <table class="table table-stripped table-hover">
            <thead>
            <tr>
                <th>&nbsp;</th>
                <th>Issue</th>
                <th>Kind</th>
                <th>Priority</th>
                <th>Status</th>
                <th>Product</th>
                <th>&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            {% for issue in issue_list %}
                <tr class="table-header expandable">
                    <td>
                        <span class="glyphicon glyphicon-eye-open"></span>
                    </td>
                    <td>
                        {{ issue.issue_text }}
                    </td>
                    <td>
                        {{ issue.issue_kind }}
                    </td>
                    <td>
                <span class="label
                {% if issue.issue_priority.issue_priority_weight == 0 %}
                label-danger
                {% elif issue.issue_priority.issue_priority_weight == 1 %}
                label-warning
                {% else %}
                label-default
                {% endif %}
                ">{{ issue.issue_priority }}</span>
                    </td>

                    <td>
                        {{ issue.issue_status }}
                    </td>
                    <td>
                        {{ issue.issue_product }}
                    </td>

                    <td><a href="{% url 'issue_edit' issue.pk %}">
                        <span class="glyphicon glyphicon-edit"></span>
                    </a>
                    </td>
                </tr>
                <tr class="table-footer">
                    <td colspan="8">
                        <div>
                            <p><strong>Creator</strong>: {{ issue.issue_creator }}</p>

                            <p><strong>Assignee</strong>: {{ issue.issue_assignee }}</p>

                            <p><strong>Description</strong>: {{ issue.issue_description }}</p>

                            <form action="{% url 'issue_edit' issue.pk %}" method='GET' ">{% csrf_token %}
                                <input type="submit" class="btn btn-group-vertical btn-primary" value="Edit Issue"/>
                            </div>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% else %}
        <h3>No issues.</h3>
    {% endif %}

{% endblock %}

issue_tracker/templates/issue_tracker/issue_delete.html
{% extends 'issue_tracker/base.html' %}
{% block content %}

    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm"/>
    </form>

{% endblock %}

issue_tracker/templates/issue_tracker/issue_edit.html
{% extends 'issue_tracker/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h3 style="text-align: center">{{ issue.issue_text }}
            <small>edit</small>
        </h3>
        <form action="" class="list-group" method="POST">{% csrf_token %}
            <ul class="list-group">
            {% for field in form.visible_fields %}
                <li class="list-group-item"><p>{{ field.label_tag }}<p>{{ field }}</li>
            {% endfor %}
            </ul>
            <input type="submit" class="btn btn-success" placeholder="issue text" value="Save">
            {% if issue.pk %}
            <input type="submit" formaction="{% url 'issue_delete' pk=issue.pk %}" method="post" value="delete"
            class="btn btn-danger">

            {% endif %}
        </form>
    </div>
</div>

{% endblock %}

issue_tracker/templates/issue_tracker/login.html
{% extends "issue_tracker/base.html" %}

{% block content %}
    <form action=""  method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="Login"></input>
        <h5>Haven't registered yet? Click <a href="{% url 'register' %}">Here</a> to register </h5>
</form>
{% endblock %}

issue_tracker/templates/issue_tracker/logout.html
{% extends "base.html" %}

{% block content %}

Logged out!

{% endblock %}

issue_tracker/templates/issue_tracker/register.html
{% extends 'issue_tracker/base.html' %}
{% block content %}
    
    <form action="" class="list-group" method="POST">{% csrf_token %}
            <ul class="list-group">
            {% for field in form.visible_fields %}
                <li class="list-group-item"><p>{{ field.label_tag }}<p>{{ field }}</li>
            {% endfor %}
            </ul>
            <input type="submit" class="btn btn-success" placeholder="issue text" value="Save">
            {% if issue.pk %}
            <input type="submit" formaction="{% url 'issue_delete' pk=issue.pk %}" method="post" value="delete"
            class="btn btn-danger">

            {% endif %}
        </form>

{% endblock %}